server:
  port: 8750
debug: false
logging:
  level: 
   org:
    apache: info
  file: my.log
spring:
  application:
    name: eureka-client
eureka:
  client:
#    healthcheck:
#      enabled: true #eureka.client.healthcheck.enabled=true只能在application.yml中设置。设置bootstrap.yml中的值将导致不期望的副作用，例如在具有UNKNOWN状态的eureka中注册
    instance:
      hostname: eureka.client
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/,http://peer4:8764/eureka/