server:
  port: 8752
spring:
  application:
    name: eureka-client2
eureka:
  client:
    leaseRenewalIntervalInSeconds: 0
    instance:
      hostname: eureka.client2
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/,http://peer4:8764/eureka/