#server:
#  port: 8889
#
##请求url格式：请求例子：http://localhost:8888/{application}/{profile}/{label},{application}会默认匹配application开头，{label}可以没有，默认为master
#spring:
#  application:
#    name: config-server-by-client
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Mingo-xoto/spring-cloud-repo #不匹配repos下的任何模式则启用该默认
##          basedir: target/config
##          searchPaths: config-repo
##          force-pull: true
##          cloneOnStart: true
##          repos:
##            config-repo2: #请求例子：http://localhost:8888/config-repo2/test获取config-repo2-test.yaml，http://localhost:8888/config-repo2-redis/prd或http://localhost:8888/config-repo2/redis-prd获取config-repo2-redis-prd.yaml
##              pattern: config-repo2*
##              uri: https://github.com/Mingo-xoto/spring-cloud-repo2
##              cloneOnStart: true
##              force-pull: true
##              basedir: target/config2
##              searchPaths: config-repo2
##            config-repo1: #请求例子：http://localhost:8888/config-repo1/test获取application-test.yaml，http://localhost:8888/config-repo1/redis-prd获取application-redis-prd.yaml
##              pattern: config-repo1*
##              uri: https://github.com/Mingo-xoto/spring-cloud-repo
##              cloneOnStart: true
##              force-pull: true
##              basedir: target/config1
##              searchPaths: config-repo1
